version: '3.8'
services:
    java-maven-app: 
      image: kelzceana/demo-app:1.4
      ports:
       - 8080:8080
    postgress:
      image: postgress:13
      ports:
        - 5432:5432
      environment:
        - POSTGRES_PASSWORD=my_pwd
      
    